site_name: PyValidX
site_description: Custom field validation for Python with Pydantic
site_author: Harrison Alonso Arroyave Gaviria
site_url: https://harrison-gaviria.github.io/pyvalidx

repo_name: harrison-gaviria/pyvalidx
repo_url: https://github.com/harrison-gaviria/pyvalidx

theme:
  name: material
  palette:
  # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Basic Concepts: getting-started/basic-concepts.md
  - Validators:
    - Core Validators: validators/core.md
    - String Validators: validators/string.md
    - Numeric Validators: validators/numeric.md
    - Date Validators: validators/date.md
    - Type Validators: validators/types.md
  - Advanced Usage:
    - Custom Validators: advanced/custom-validators.md
    - Conditional Validation: advanced/conditional-validation.md
    - Error Handling: advanced/error-handling.md
    - Model Validation: advanced/model-validation.md
  - API Reference:
    - ValidatedModel: api-reference/validated-model.md
    - field_validated: api-reference/field-validated.md
    - ValidationException: api-reference/validation-exception.md
  - Examples:
    - Overview: examples/README.md
    - User Registration: examples/user-registration.md
    - Form Validation: examples/form-validation.md
    - API Validation: examples/api-validation.md
